#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys, os, shutil, fileinput

# get stdin param len(ginput) == 3
ginput = []
refname = []
branch = ''

print '[自动化部署] 获取commit、分支信息...'
for line in fileinput.input():
    ginput = line.split(' ')
print ginput

# get branch from ref-name: refs/heads/[branch]
refname = ginput[2].split('/')
if len(refname) == 3:
    branch = refname[2].replace('\n','')
else:
    print '推送refname异常，请联系 半边 review'
    sys.exit(1)
print branch

# xxx.git
bareRepo = os.path.basename(os.getcwd())
# xxx_deploy
deployRepo = bareRepo[0:-4]

print '[自动化部署] 定位切换、清理...'
os.chdir('../')
if os.path.exists(deployRepo):
    shutil.rmtree(deployRepo)
    #os.mkdir(deployRepo)

print '[自动化部署] 获取静态资源...'
os.system('git clone -q -b ' + branch + ' ' + bareRepo)

print os.listdir(deployRepo)
print open(deployRepo + "/dist/README.md").read().replace('\n','-')
#os.system('cd ' + deployRepo + ' && git checkout develop && git pull origin develop && ls')
print 'Hello, ' + os.getcwd()
